### PR TITLE
Fix html invalid attribute

### PR DESCRIPTION
**Pull request by nicoschi**
Use data-ie-style instead of ie-style for inline styles in order to pass html validation

### CODE REVIEW

**Comment by nuxodin** [comment]
Thank you for your PR.
Since custom attributes are well supported, even if not (yet) specified. I would like to keep it that way. Also to remain compatible.

**Comment by nicoschi** [comment]
Is there some documentation about future implementation of html custom attributes by W3C?

**Comment by nuxodin** [comment]
Here is the discussion:
https://github.com/whatwg/html/issues/2271

As I said, it is not specified and may never be specified, but since all browsers allow it, it can be used (carefully).

By the way, "data-" attributes are less intended to be used for independent frameworks, but rather for project-specific data.
https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes
```
Custom data attributes are intended to store custom data, state, annotations, and similar, private to the page or application,
```

**Comment by nicoschi** [comment]
I know, but sometimes projects require W3C validation. Nevermind, I will use a patched version. Thanks

**Pull request closed without merging**
