### PR TITLE
Update ie11CustomProperties.js

### PR DESCRIPTION
**Pull request by sbatezat**
Support of "pure_getters" compress options

### CODE REVIEW

**Comment by nuxodin** [comment]
Good catch, thank you!

**Comment by sbatezat** [comment]
You'r welcome!
When can we expect a new npm release (3.1.1?) with that fix? I really need it! 
Thanks

**Comment by nuxodin** [comment]
Its online, 4.0.0
https://www.npmjs.com/package/ie11-custom-properties

**Comment by sbatezat** [comment]
Thanks for this quick update! I've juste updated the npm package and all is working as expected

**Pull request merged**
